product_homepage:
    path:     /
    defaults: { _controller: ProductBundle:Default:index }
    
product_list:
    path:     /list
    defaults: { _controller: ProductBundle:Default:list }
    
product_create:
    path:     /create/{nom}/{descripcio}/{preu}
    defaults: { _controller: ProductBundle:Default:create }
    
product_read:
    path:     /read/{id}
    defaults: { _controller: ProductBundle:Default:read }
    
product_update:
    path:     /update/{id}/{nom}/{descripcio}/{preu}
    defaults: { _controller: ProductBundle:Default:update }
    
product_delete:
    path:     /delete/{id}
    defaults: { _controller: ProductBundle:Default:delete }

product_dql:
    path:     /dql/{preu1}/{preu2}
    defaults: { _controller: ProductBundle:Default:dql }

product_preuigual:
    path:     /igual/{preu}
    defaults: { _controller: ProductBundle:Default:igual }

product_sql:
    path:     /sql/{preu}/{lletres}
    defaults: { _controller: ProductBundle:Default:sql }

product_form:
    path:     /form
    defaults: { _controller: ProductBundle:Default:form } 