<?php

namespace ProductBundle\Repository;

/**
 * ProducteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducteRepository extends \Doctrine\ORM\EntityRepository
{
}
